FROM rust:1.75

WORKDIR /app

# Install Godot for E2E tests
RUN apt-get update && apt-get install -y wget unzip
RUN wget https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip
RUN unzip Godot_v4.3-stable_linux.x86_64.zip -d /usr/local/bin/
RUN mv /usr/local/bin/Godot_v4.3-stable_linux.x86_64 /usr/local/bin/godot

# Install iproute2 for tc netem
RUN apt-get install -y iproute2

WORKDIR /app
COPY . .

CMD ["/bin/bash"]
